prueba con text.txt

diff --git a/buildspecCI.yml b/buildspecCI.yml
--- a/buildspecCI.yml
+++ b/buildspecCI.yml
@@ -4,7 +4,7 @@ phases:
   pre_build:
     commands:
       - pip install -r requirements.txt
-      - touch text.txt
+      
   build:
     commands:
       - export FLASK_ENV=testing
@@ -14,11 +14,20 @@ phases:
   post_build:
     commands:
       # Save the Docker image as a tar file
-      - docker build -t compumundo-black-list-ci-container-image .
-      - docker save compumundo-black-list-ci-container-image:latest -o docker-image.tar
-      - gzip docker-image.tar
+      #- docker build -t compumundo-black-list-ci-container-image .
+      #- docker save compumundo-black-list-ci-container-image:latest -o docker-image.tar
+      #- gzip docker-image.tar
+      - |
+        if [ $CODEBUILD_BUILD_SUCCEEDING = 1 ]; then
+          echo "Build succeeded, running post-build steps"
+          touch text.txt
+        else
+          echo "Build failed, skipping post-build steps"
+          exit 1
+        fi
 
 artifacts:
   files:
-    - docker-image.tar.gz
+    #- docker-image.tar.gz
+    - text.txt
   name: docker-image-$(date +%Y-%m-%d_%H-%M)
