ajuste buildspecCI

diff --git a/buildspecCI.yml b/buildspecCI.yml
--- a/buildspecCI.yml
+++ b/buildspecCI.yml
@@ -8,7 +8,11 @@ phases:
   build:
     commands:
       - export FLASK_ENV=testing
-      - pytest tests/ || exit 1
+      - |
+        if ! pytest tests/; then
+          echo "Tests failed"
+          exit 1
+        fi
       
   post_build:
     commands:
